[python]
embed = true

[application]
name = "Revision"
main_module = "main"

# List any additional modules your application uses here
[[python.module]]
name = "modules.Conjugation"

[[python.module]]
name = "modules.Grammar"

[[python.module]]
name = "modules.Vocabulary"

[[python.module]]
name = "modules.Solution"

[[python.module]]
name = "utils.Buttons"

[[python.module]]
name = "utils.SwitchScreen"

# Include PyQt5 package
[[python.package]]
name = "PyQt5"
include_dirs = true

# Include UI files
[[python.data_file]]
source = "ui/conjugationLevelPage.ui"
destination = "ui/conjugationLevelPage.ui"

[[python.data_file]]
source = "ui/conjugationMenuPage.ui"
destination = "ui/conjugationMenuPage.ui"

[[python.data_file]]
source = "ui/grammarMenuPage.ui"
destination = "ui/grammarMenuPage.ui"

[[python.data_file]]
source = "ui/grammarLevelPage.ui"
destination = "ui/grammarLevelPage.ui"

[[python.data_file]]
source = "ui/vocabularyLevelPage.ui"
destination = "ui/vocabularyLevelPage.ui"

[[python.data_file]]
source = "ui/vocabularyMenuPage.ui"
destination = "ui/vocabularyMenuPage.ui"


# Include JSON file
[[python.data_file]]
source = "database/dictionary.json"
destination = "database/dictionary.json"
